---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "order-tracking"
  namespace: "default"
  labels:
    app: "order-tracking"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "order-tracking"
  template:
    metadata:
      labels:
        app: "order-tracking"
    spec:
      containers:
      - name: "gke-order-tracking"
        image: gcr.io/main-canyon-273521/gke-order-tracking
        imagePullPolicy: Always
        env:
          - name: REDISHOST
            valueFrom:
              configMapKeyRef:
                name: redishost
                key: REDISHOST
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "order-tracking-hpa-kkdr"
  namespace: "default"
  labels:
    app: "order-tracking"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "order-tracking"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
