---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "order-tracking"
  namespace: "default"
  labels:
    app: "order-tracking"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "order-tracking"
  template:
    metadata:
      labels:
        app: "order-tracking"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "order-tracking-hpa-kkdr"
  namespace: "default"
  labels:
    app: "order-tracking"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "order-tracking"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
