---
  apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "order-tracking-service"
    namespace: "default"
    labels:
      app: "order-tracking"
  spec:
    ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
    selector:
      app: "order-tracking"
    type: "LoadBalancer"
  